# org.gradle.java.home=C\:\\Program Files\\JetBrains\\IntelliJ IDEA Community Edition 2025.2.5\\jbr
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official

# Increase heap size to prevent OutOfMemoryError during DEX merging
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

